import './globals.css'
import { Footer } from './Components/footer'
import { Header } from './Components/header'
import { Inter } from 'next/font/google'
import Home from './page'
import Nosotros from './nosotros/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Burbujitas - Kinder Garden</title>
      </head>
      <body className={inter.className}>
        <Header />
        
        {children}

        <Footer />
      </body>
    </html>
  )
}
